### ISSUE TITLE
Identificación de productos

### ISSUE THREAD

**Issue by NachoCarher** [NachoCarher/MyHams#13]
Como empresario, quiero que el sistema cuente con una serie de productos con sus respectivos detalles e información. Pues entre ellos quiero poder elegir cuáles son los que voy a vender en mi negocio, en qué cantidad y a qué precio. #7

**Comment by JJ** [comment]
Las HUs deben tener relación con la lógica de negocio y algún beneficio para el usuario. En este caso, se trata simplemente de información que tú, como programador, quieres que el usuario proporcione.
