### ISSUE TITLE
[Fix] Fallos en HU4

### ISSUE THREAD

**Issue by Parka015** [NachoCarher/MyHams#14]
La historia de usuario 4 tiene como titulo, crear un perfil de usuario pero en la descripción es el empresario el que lo pide, también arregla el pequeño detalle de [H4] que debería ser [HU4]

**Comment by Parka015** [comment]
Okay, puedes cerrar este issue

**Comment by JJ** [comment]
Sin identificación de producto como indica #13 no se puede hacer nada. Lo que ocurre es que no es una HU, sino un issue.
