### ISSUE TITLE
[Fix] Faltan issues para Milestone 0

### ISSUE THREAD

**Issue by Parka015** [NachoCarher/MyHams#8]
Un milestone no puede estar vacío por lo que falta una HU que justifique la creación de una estructura de datos para guardar la información de los productos

**Comment by Parka015** [comment]
[Fix] Faltan issues para M0

Un milestone no puede estar vacío por lo que falta una HU que justifique la creación de una estructura de datos para guardar la información de los productos

**Comment by Parka015** [comment]
Okay, pues puedes cerrar este issue

**Comment by JJ** [comment]
Lo que tendrías que modificar es la denominación de HUs de algunos. #13 sería parte de una verdadera HU que podría ser la #7
